using Autodesk.GUIHarness.Plant3D.CmdOptScripts;
using Autodesk.GUIHarness.AutoCAD.TestSuites.GlobalCmdOpt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using LAGT.CommonFiles.Classes;

namespace Autodesk.GUIHarness.Plant3D.TestSuites.GlobalCmdOpt
{
    public class CmdOpt_Setup
    //Function code from CmdOpt_Lists.inc of AutoCAD
    {
        // Enable the Harness watchdog
        public bool bUseKill = true;

        // Set the Harness watchdog timer
        public int iRecoverBatWaitTime = 30000; //PRADIP - used from LAF, need to check if this much time is required...

        public static List<List<Command>> llCommands_FAILING = new List<List<Command>>();
        // Put here the Commands you want to re-execute and ...
        // set to TRUE the 'bFailingsList' variable in the CmdOpt2_Setup.inc file
        // i.e. the commands that are failing in a first execution


        public static List<List<Command>> llCommands_Postrio = new List<List<Command>>();
        // Put here the Commands you want to include as Postrio commands (new or modified in Postrio/Tokyo)
        // Set to TRUE the 'bPostrioCmdList' variable in the CmdOpt2_Setup.inc file

        // POSTRIO/TOKYO Commands
        // List according to shouthpark commnads list (last update: dd/mm/yyyy)

        //jv: not necessary at the moment. Using tCurrentCmd.bPostrioCmd instead when CreateGroupList function

        public static List<List<Command>> llCommands_ALL = new List<List<Command>>()
        {
             //************ Moonshine Extenstion 1 new commands************
            //new PLANTPCFTOPIPECLASS().lcPLANTPCFTOPIPE,
            //new PLANTISOADDREFDIMCLASS().lcPLANTISOADDREFDIM,
            //*************************************************************


            //new PLANTPCFTOPIPECLASS().lcPLANTPCFTOPIPE,
            new PLANTISOADDREFDIMCLASS().lcPLANTISOADDREFDIM,
			new AUDITPROJECTCLASS().lcAUDITPROJECT,
			new AUTODESKCONNECTIONPOINTCLASS().lcAUTODESKCONNECTIONPOINT,
			new DataManagerClose_DBCLASS().lcDataManagerClose_DB,
			new NEWPROJECTDWGCLASS().lcNEWPROJECTDWG,
			new OFFPAGECONNECTCLASS().lcOFFPAGECONNECT, 
			new PLANTCOMPASSCLASS().lcPLANTCOMPASS,
			new PLANTCONNECTJOINTCLASS().lcPLANTCONNECTJOINT,
			new PLANTCONVERTLINETOPIPECLASS().lcPLANTCONVERTLINETOPIPE,
			new PLANTCREATEREPORT_DBCLASS().lcPLANTCREATEREPORT_DB,
			new PLANTCUSTOMPARTS_DBCLASS().lcPLANTCUSTOMPARTS_DB,
			new PLANTDWGCHECKERCLASS().lcPLANTDWGCHECKER, 
			new PlantDWGCheckerAutoCheckCLASS().lcPlantDWGCheckerAutoCheck,
			new PLANTDYNAMICTOOLPALETTECLASS().lcPLANTDYNAMICTOOLPALETTE,
			new PLANTEDITAUTODESKCONNECTIONPOINTCLASS().lcPLANTEDITAUTODESKCONNECTIONPOINT,
			new PLANTEDITBENDCLASS().lcPLANTEDITBEND,
			new PLANTEDITCOGCLASS().lcPLANTEDITCOG, 
			new PLANTEQUIPMENTATTACHCLASS().lcPLANTEQUIPMENTATTACH,
			new PLANTEQUIPMENTCONVERTCLASS().lcPLANTEQUIPMENTCONVERT,
			new PLANTEQUIPMENTCREATECLASS().lcPLANTEQUIPMENTCREATE,
			new PLANTEQUIPMENTDETACHCLASS().lcPLANTEQUIPMENTDETACH,
			new PLANTFITTINGADDCLASS().lcPLANTFITTINGADD,
			new PLANTFITTINGADD_DBCLASS().lcPLANTFITTINGADD_DB,
			new PLANTFITTINGMOVECLASS().lcPLANTFITTINGMOVE, 
			new PLANTGRIPEDITMODECLASS().lcPLANTGRIPEDITMODE,
			new PLANTHIDECLASS().lcPLANTHIDE,
			new PLANTINSERTAUTODESKCONNECTIONPOINTCLASS().lcPLANTINSERTAUTODESKCONNECTIONPOINT,
			new PLANTISOADDINFOCLASS().lcPLANTISOADDINFO,
			new PLANTISOLATECLASS().lcPLANTISOLATE,
			new PLANTISOTBATTRIBUTESETUPCLASS().lcPLANTISOTBATTRIBUTESETUP,
			new PLANTISOTBCLOSECLASS().lcPLANTISOTBCLOSE,
			new PLANTISOTBDRAWAREACLASS().lcPLANTISOTBDRAWAREA,
			new PLANTISOTBNORTHARROWCLASS().lcPLANTISOTBNORTHARROW,
			new PLANTISOTBPLACETABLECLASS().lcPLANTISOTBPLACETABLE, //PLANT16-470
			new PLANTISOTHEMESSETUPCLASS().lcPLANTISOTHEMESSETUP,
			new PLANTMODIFYSHAREDCONTENTFOLDERCLASS().lcPLANTMODIFYSHAREDCONTENTFOLDER,
			new PLANTNOZZLEADDCLASS().lcPLANTNOZZLEADD,
			new PLANTNOZZLEEDITCLASS().lcPLANTNOZZLEEDIT,
			new PLANTORTHOADDJOGCLASS().lcPLANTORTHOADDJOG,
			new PLANTORTHOANNOTATECLASS().lcPLANTORTHOANNOTATE,
			new PLANTORTHOCREATECLASS().lcPLANTORTHOCREATE, //according to SQ PLANT16-252 removed from Moonshine
			new PLANTORTHOCREATE_DBCLASS().lcPLANTORTHOCREATE_DB,
			new PLANTORTHODELETECLASS().lcPLANTORTHODELETE, 
			new PLANTORTHODWGTABLESETUP_DBCLASS().lcPLANTORTHODWGTABLESETUP_DB,
			new PLANTORTHOEDITCLASS().lcPLANTORTHOEDIT,
			new PLANTORTHOHIDDENLINEMODECLASS().lcPLANTORTHOHIDDENLINEMODE,
			new PLANTORTHOLOCATECLASS().lcPLANTORTHOLOCATE,
			new PLANTORTHOMATCHLINEMODECLASS().lcPLANTORTHOMATCHLINEMODE, //sysvar PLANT16-471
			new PLANTORTHONOCENTERLINESCLASS().lcPLANTORTHONOCENTERLINES,
			new PLANTORTHOPAPERCHECKCLASS().lcPLANTORTHOPAPERCHECK,
			new PLANTORTHOPIPEGAPCLASS().lcPLANTORTHOPIPEGAP,
			new PLANTORTHOPLACEBOMCLASS().lcPLANTORTHOPLACEBOM,
			new PLANTORTHOPLACEBOMTEMPLATECLASS().lcPLANTORTHOPLACEBOMTEMPLATE,
			new PlantOrthoShowOpenPipeSymbolCLASS().lcPlantOrthoShowOpenPipeSymbol,
			new PLANTORTHOTEMPLATESETTINGSCLASS().lcPLANTORTHOTEMPLATESETTINGS,
			new PLANTORTHOTEMPLATETABLESETUP_DBCLASS().lcPLANTORTHOTEMPLATETABLESETUP_DB,
			new PLANTORTHOUPDATECLASS().lcPLANTORTHOUPDATE,
			new PLANTORTHOUPDATEANNOTATIONCLASS().lcPLANTORTHOUPDATEANNOTATION,
			new PLANTORTHOUPDATEBOMCLASS().lcPLANTORTHOUPDATEBOM,
			new PLANTPARTCONVERTCLASS().lcPLANTPARTCONVERT,
			new PLANTPIPEADDCLASS().lcPLANTPIPEADD,
			new PLANTPIPESLOPECLASS().lcPLANTPIPESLOPE,
			new PLANTPIPESUPPORTADDCLASS().lcPLANTPIPESUPPORTADD,
			new PLANTPIPESUPPORTATTACHCLASS().lcPLANTPIPESUPPORTATTACH,
			new PLANTPIPESUPPORTCONVERTCLASS().lcPLANTPIPESUPPORTCONVERT,
			new PLANTPIPESUPPORTDETACHCLASS().lcPLANTPIPESUPPORTDETACH,
			new PLANTPIPESUPPORTMOVECLASS().lcPLANTPIPESUPPORTMOVE,
			new PLANTPRODUCTIONISOCLASS().lcPLANTPRODUCTIONISO,
			new PLANTQUICKISOCLASS().lcPLANTQUICKISO,
			new PLANTREMOVEORPHANFASTENERSCLASS().lcPLANTREMOVEORPHANFASTENERS,
			new PLANTROUTEFROMAUTODESKCONNECTIONPOINTCLASS().lcPLANTROUTEFROMAUTODESKCONNECTIONPOINT,
			new PLANTSELECTIVECOGSWITCHCLASS().lcPLANTSELECTIVECOGSWITCH,
			new PLANTSHOWALLCLASS().lcPLANTSHOWALL,
			new PLANTSIZEDISPLAYMODECLASS().lcPLANTSIZEDISPLAYMODE,
			new PLANTSLOPETHRESHOLDANGLECLASS().lcPLANTSLOPETHRESHOLDANGLE, //sysvar - out of scope
			new PlantSnapshotCOGCLASS().lcPlantSnapshotCOG,
			new PLANTSTEELCUTCLASS().lcPLANTSTEELCUT,
			new PLANTSTEELEDGECUTCLASS().lcPLANTSTEELEDGECUT,
			new PLANTSTEELEDITCLASS().lcPLANTSTEELEDIT,
			new PLANTSTEELEXPLODECLASS().lcPLANTSTEELEXPLODE,
			new PLANTSTEELFOOTINGCLASS().lcPLANTSTEELFOOTING,
			new PLANTSTEELLADDERCLASS().lcPLANTSTEELLADDER,
			new PLANTSTEELLENGTHENCLASS().lcPLANTSTEELLENGTHEN,
			new PLANTSTEELMEMBERCLASS().lcPLANTSTEELMEMBER,
			new PLANTSTEELMITERCLASS().lcPLANTSTEELMITER,
			new PLANTSTEELRAILINGCLASS().lcPLANTSTEELRAILING,
			new PLANTSTEELRESTORECLASS().lcPLANTSTEELRESTORE,
			new PLANTSTEELSETREPCLASS().lcPLANTSTEELSETREP,
			new PLANTSTEELSTAIRCLASS().lcPLANTSTEELSTAIR,
			new PLANTSUPPORTSONSUPPORTSCLASS().lcPLANTSUPPORTSONSUPPORTS,
			new PLANTTAGCLASS().lcPLANTTAG,
			new PLANTTAG_DBCLASS().lcPLANTTAG_DB,
			new PLANTWELDADDCLASS().lcPLANTWELDADD,
			new ProjectManagerCloseCLASS().lcProjectManagerClose,
			new PROJECTSETUP_DBCLASS().lcPROJECTSETUP_DB,
			new ValidateSummary_DBCLASS().lcValidateSummary_DB,

        };
        // /////////////////////// Groups of Commands to Test ////////////////////

        public static List<string> lsGroupOfCommands = new List<string>() 
        {
                "PLANT3D"

        };
        public List<List<Command>> InitCmdList()
        {
            return llCommands_ALL;
        }

        public List<string> InitGroupList()
        {
            return lsGroupOfCommands;
        }
    }
}
